[package]
name = "android-bridge"
version = "0.1.0"
edition = "2024"

[lib]
name = "android_bridge"
path = "src/android_bridge.rs"
crate-type = ["cdylib"]

[dependencies]
simple-core = { path = "../simple-core" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
jni = "0.21"
