#!/usr/bin/env sh
set -e
cd "$(dirname "$0")/.."
ANDROID_NDK_HOME=~/Library/Android/sdk/ndk/27.3.13750724 cargo ndk -t arm64-v8a -t armeabi-v7a -t x86_64 --platform 24 -o android/app/src/main/jniLibs build -p android-bridge --release
