[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
crossterm = { version = "0.29", features = ["serde", "event-stream"] }
dirs = { workspace = true }
futures = { workspace = true }
ratatui = { version = "0.30", features = ["unstable-widget-ref"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.50", features = ["full"] }
tokio-util = "0.7"
chrono = { workspace = true }
tachyonfx = "0.25"
once_cell = "1.21"
tui-scrollview = "0.6.4"
tui-widget-list = "0.15.2"
tui-input = { version = "0.15", features = ["crossterm"] }

uuid = { workspace = true }

simple-core = { path = "../simple-core" }
simple-db = { path = "../simple-db" }
simple-parser = { path = "../simple-parser" }
