[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui_transitions = { path = "/Users/felixb/Projects/gpui_transitions" }
open = { workspace = true }
app-core = { workspace = true }
database = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
unicode-segmentation = { workspace = true }
schemars = { workspace = true }
smol = { workspace = true }
smallvec = { workspace = true }
rust-embed = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
fuzzy-matcher = { workspace = true }
